cmake_minimum_required(VERSION 3.20)
project(Oh-STL)

file(GLOB_RECURSE STL_HEADERS CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/Public/*.h")
file(GLOB_RECURSE STL_SOURCE CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/Private/*.cpp")

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

source_group(TREE ${CMAKE_CURRENT_SOURCE_DIR} FILES
    ${STL_HEADERS}
    ${STL_SOURCE}
)

add_executable(Oh-STL  ${STL_SOURCE} ${STL_HEADERS})

target_include_directories(Oh-STL PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/src/Public)

